checksumBehavior: update

enableGlobalCache: false

enableImmutableInstalls: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: pnpm

npmScopes:
  metalabsog:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
