nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local

npmScopes:
  metalabsog:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"
