nodeLinker: node-modules
checksumBehavior: 'update'
enableGlobalCache: false
enableHyperlinks: true
enableImmutableInstalls: true
npmScopes:
    metalabsog:
        npmAlwaysAuth: true
        npmAuthToken: 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
        npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-sources.cjs
