import { TinymanDex } from './dexesProvider';
import json_tests from './logicsig_tests.json';

// Tests pool addresses with those generated by python tinyman sdk
test('tinyman logicsig calculation', () => {
     //@ts-ignore
    const dex = new TinymanDex(undefined);

    for (const t of json_tests) {
        const lSigAddr = dex.getPoolLogicSig(t.a1, t.a2, t.v_id).address();
        expect(lSigAddr).toEqual(t.addr);
    }
});