import * as Tinyman from './Tinyman';
import json_tests from './logicsig_tests.json';

// Tests pool addresses with those generated by python tinyman sdk
test('tinyman logicsig calculation', () => {
    for (const t of json_tests) {
        const lSigAddr = Tinyman.getPoolLogicSig(t.a1, t.a2, t.v_id).address();
        expect(lSigAddr).toEqual(t.addr);
    }
});
